customer/urls.py
from django.conf.urls import url
from . import views

app_name = "customer"

urlpatterns = [
    url(r'^$', views.create, name="create"),
    url(r'^list/$', views.list, name="list"),
    url(r'^update/(?P<pk>\d+)$', views.update, name="update"),
    url(r'^delete/(?P<pk>\d+)$', views.delete, name="delete"),
    url(r'^trash/$', views.trash_list, name="trash_list"),
]

transaction/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^customers/', include('customer.urls')),
    url(r'^items/', include('item.urls')),
    url(r'^units/', include('unit.urls')),
    url(r'^transactions/', include('txn.urls')),
]

txn/urls.py
from django.conf.urls import url
from . import views

app_name = "txn"

urlpatterns = [
    url(r'^index/$', views.index, name="index"),
    url(r'^list/$', views.list, name="list"),
    url(r'^paid/(?P<pk>\d+)/$', views.paid, name="paid"),
]

customer/models.py
from django.db import models


# Create your models here.
class Customer(models.Model):
    cname = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    phone_no = models.CharField(max_length=15)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        db_table = "customer"
        verbose_name = "Customer"
        verbose_name_plural = "Customers"

    def __str__(self):
        return str(self.cname)

customer/forms.py
from django import forms
from .models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = [
            'cname',
            'address',
            'phone_no',
        ]
        widgets = {
            'cname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Customer Name'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'phone_no': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone Number'}),
        }

customer/views.py
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import CustomerForm
from .models import Customer


# from item.views import create


# Create your views here.
def create(request):
    form = CustomerForm(request.POST or None)
    context = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect("customer:list")
    context['form'] = form
    return render(request, 'customer/create.html', context)


def update(request, pk):
    context = {}
    try:
        data = Customer.objects.get(id=pk)
    except Customer.DoesNotExist:
        messages.error(request, "Object Not Found")
        return redirect("customer:list")

    form = CustomerForm(instance=data)
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return redirect("customer:list")

    context['form'] = form
    return render(request, 'customer/create.html', context)


def delete(request, pk):
    context = {}
    choice = request.GET.get('choice')
    context['status'] = choice

    if request.method == "POST":
        try:
            data = Customer.objects.get(id=pk)
        except Customer.DoesNotExist:
            messages.error(request, "Customer not found")
            return redirect("customer:list")

        if choice == "undo":
            data.is_deleted = False
            data.save()
            messages.success(request, 'Undo successfully.')

        elif choice == "Trash":
            data.is_deleted = True
            data.save()
            messages.success(request, 'Trashed successfully.')

        elif choice == "delete" and data.is_deleted is True:
            data.delete()
            messages.success(request, 'Deleted successfully.')

        return redirect("customer:list")

    context['url'] = reverse("customer:list")
    return render(request, 'snippest/delete.html', context)


def list(request):
    context = {}
    data = Customer.objects.all()

    per_page = 2
    paginator = Paginator(data, per_page)
    page = request.GET.get('page')
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    context['data'] = data
    return render(request, 'customer/list.html', context)


def trash_list(request):
    context = {}
    data = Customer.objects.filter(is_deleted=True)

    per_page = 2
    paginator = Paginator(data, per_page)
    page = request.GET.get('page')
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    context['data'] = data
    return render(request, 'customer/list.html', context)

customer/templates/customer/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block breadcrumb_link %}
    <li class="breadcrumb-item"><a href="{% url 'customer:list' %}">Customer</a></li>
    <li class="breadcrumb-item active" aria-current="page">New</li>
{% endblock %}

{% block content %}
    <div class="container" id="form_layout">
        <div class="row mt-5">
            <div class="col-md-8 offset-md-2">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Customer Name</label>
                        {% if form.cname.errors %}
                            <div class="col-sm-8">
                                {{ form.cname | add_class:"is-invalid" }}
                                <div class="invalid-feedback">
                                    {{ form.cname.errors }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-sm-8">
                                {{ form.cname }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Address</label>
                        {% if form.address.errors %}
                            <div class="col-sm-8">
                                {{ form.address | add_class:"is-invalid" }}
                                <div class="invalid-feedback">
                                    {{ form.address.errors }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-sm-8">
                                {{ form.address }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Phone Number</label>
                        {% if form.phone_no.errors %}
                            <div class="col-sm-8">
                                {{ form.phone_no | add_class:"is-invalid" }}
                                <div class="invalid-feedback">
                                    {{ form.phone_no.errors }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-sm-8">
                                {{ form.phone_no }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-8 offset-sm-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

customer/templates/customer/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block breadcrumb_link %}
    <li class="breadcrumb-item active" aria-current="page">Customer</li>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <a href="{% url 'customer:create' %}" class=" btn btn-primary"><i class="fa fa-plus"> </i> Add</a>
        </div>
        <br>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Customer Name</th>
                        <th>Address</th>
                        <th></th>
                    </tr>
                    </thead>
                    {% for datum in data %}
                        <tr>
                            <td> {{ datum.cname }} </td>
                            <td> {{ datum.address }} </td>
                            <td>
                                {% if not datum.is_deleted %}
                                    <a href="{% url 'customer:update' datum.id %}" class=" btn">
                                        <i class="fa fa-2x fa-pencil-square-o"></i>
                                    </a>
                                    <a href="{% url 'customer:delete' datum.id %}?choice=Trash" class=" btn">
                                        <i class="fa fa-2x fa-trash-o text-danger"></i>
                                    </a>
                                {% else %}
                                    <a href="{% url 'customer:delete' datum.id %}?choice=undo" class=" btn">
                                        <i class="fa fa-2x fa-undo"></i>
                                    </a>
                                    <a href="{% url 'customer:delete' datum.id %}?choice=delete" class=" btn">
                                        <i class="fa fa-2x fa-trash text-danger"></i>
                                    </a>
                                {% endif %}
                            </td>

                        </tr>
                    {% empty %}
                        <tr>
                            <td class="table-danger text-center" colspan="6">No Data</td>
                        </tr>
                    {% endfor %}

                </table>

                <div class="text-center">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if data.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ data.previous_page_number }}" tabindex="-1">&laquo;
                                        Previous</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link" href="#">&laquo; Previous</a></li>
                            {% endif %}

                            {% for i in data.paginator.page_range %}
                                {% if data.number == i %}
                                    <li class="page-item disabled">
                                        <a class="page-link " href="#">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}


                            {% if data.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}">Next
                                    &raquo;</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link">Next &raquo;</a></li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}