transaction/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^customers/', include('customer.urls')),
    url(r'^items/', include('item.urls')),
    url(r'^units/', include('unit.urls')),
    url(r'^transactions/', include('txn.urls')),
]

txn/urls.py
from django.conf.urls import url
from . import views

app_name = "txn"

urlpatterns = [
    url(r'^index/$', views.index, name="index"),
    url(r'^list/$', views.list, name="list"),
    url(r'^paid/(?P<pk>\d+)/$', views.paid, name="paid"),
]

txn/models.py
from django.db import models
from customer.models import Customer
from item.models import Item


class Transactions(models.Model):
    cname = models.ForeignKey(Customer, related_name="transactions", on_delete=models.DO_NOTHING)
    itemname = models.ForeignKey(Item, related_name='itemname', on_delete=models.CASCADE)
    quantity = models.CharField(max_length=120)
    total = models.CharField(max_length=120)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        db_table = 'transactions'
        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'

    def __str__(self):
        return str(self.cname)

    def clean(self):
        pass

    def is_paid(self):
        if str(self.cname).lower() == "cash":
            return True
        return False

txn/forms.py
from django import forms
from .models import Transactions


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transactions
        fields = [
            'cname',
            'itemname',
            'quantity',
            'total',
        ]

        widgets = {
            'cname': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Customer Name'}),
            'itemname': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Select Item'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'total': forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['cname'].empty_label = "Customer Name"
        self.fields['itemname'].empty_label = "Item Name"
        # self.fields['cname'].widget.attrs['class'] = "form-control"

txn/views.py
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect
from .forms import TransactionForm
from .models import Transactions
from .models import Customer


# Create your views here.
def index(request):
    form = TransactionForm(request.POST or None)
    context = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Transaction Saved.')
            return redirect('txn:index')

    context['form'] = form
    return render(request, 'txn/index.html', context)


def list(request):
    context = {}
    data = Transactions.objects.all()

    per_page = 5
    paginator = Paginator(data, per_page)
    page = request.GET.get('page')
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    context['data'] = data
    return render(request, 'txn/list.html', context)


def paid(request, pk):
    context = {}
    data = Transactions.objects.filter(id=pk).first()
    if request.method == 'POST':
        data.cname = Customer.objects.get(cname__iexact='cash')
        data.save()
        return redirect('txn:list')

    context['cname'] = data
    return render(request, 'snippest/paid.html', context)

txn/templates/txn/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block breadcrumb_link %}
    <li class="breadcrumb-item"><a href="{% url 'txn:list' %}">Transaction</a></li>
    <li class="breadcrumb-item active" aria-current="page">New</li>
{% endblock %}

{% block content %}
    <div class="container" id="form_layout">
        <div class="row mt-5">
            <div class="col-md-8 offset-md-2">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" >Customer Name</label>
                        {% if form.cname.errors %}
                            <div class="col-sm-8">
                                {{ form.cname | add_class:"is-invalid" }}
                                <div class="invalid-feedback">
                                    {{ form.cname.errors }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-sm-8">
                                {{ form.cname }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" id="id_item">Item Name</label>
                        {% if form.itemname.errors %}
                            <div class="col-sm-8">
                                {{ form.itemname | add_class:"is-invalid" }}
                                <div class="invalid-feedback">
                                    {{ form.itemname.errors }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-sm-8">
                                {{ form.itemname }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Quantity</label>
                        {% if form.quantity.errors %}
                            <div class="col-sm-8">
                                {{ form.quantity | add_class:"is-invalid" }}
                                <div class="invalid-feedback">
                                    {{ form.quantity.errors }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-sm-8">
                                {{ form.quantity }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Total</label>
                        <div class="col-sm-8">
                            {{ form.total }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-8 offset-sm-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}


{% block extra_scripts %}
    <script>
        $('body').on('input', '#id_quantity', function () {
            var id = $('#id_itemname').val();
            var value = $(this).val();
            $.ajax({
                type: 'json',
                method: 'GET',
                url: '/items/unit-price/'+ id +'/',
                error: function () {
                    console.log("error");
                },
                success: function (data) {
                    var price = data['unit_price'];
                    var total = value * price;
                    $('#id_total').val(total);
                },
            });

        });
    </script>
{% endblock %}

txn/templates/txn/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <div class="row">
            <a href="{% url 'txn:index' %}" class=" btn btn-primary"><i class="fa fa-plus"></i> Add</a>
        </div>
        <br>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>S.N</th>
                        <th>Customer Name</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                        <th>Transaction Date</th>
                        <th>paid</th>
                    </tr>
                    </thead>
                    {% for datum in data %}
                        <tr>
                            <td> {{ forloop.counter }} </td>
                            <td> {{ datum.cname }} </td>
                            <td> {{ datum.quantity }} </td>
                            <td> {{ datum.total }} </td>
                            <td> {{ datum.created_at }} </td>
                            <td>
                                <input type="checkbox" class="paid-checkbox"{% if datum.is_paid %} checked disabled
                                       %} {% endif %}
                                       id="{{ datum.id }}">
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="table-danger" colspan="6">No Data</td>
                        </tr>
                    {% endfor %}

                </table>

                <div class="text-center">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if data.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ data.previous_page_number }}" tabindex="-1">&laquo; Previous</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link" href="#">&laquo; Previous</a></li>
                            {% endif %}

                            {% for i in data.paginator.page_range %}
                                {% if data.number == i %}
                                    <li class="page-item disabled">
                                        <a class="page-link " href="#">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}


                            {% if data.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}">Next
                                    &raquo;</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link">Next &raquo;</a></li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_scripts %}
    <script>
        $('body').on('change', '.paid-checkbox', function () {
            var id = $(this).attr('id');
            if ($(this).prop('checked') == true) {
                window.location.href = '/transactions/paid/' + id + '/';
            }
        });
    </script>
{% endblock %}