item/urls.py
from django.conf.urls import url
from . import views

app_name = "item"

urlpatterns = [
    url(r'^list/$', views.list, name="list"),
    url(r'^create/$', views.create, name="create"),
    url(r'^edit/(?P<pk>\d+)/$', views.edit, name="edit"),
    url(r'^unit-price/(?P<pk>\d+)/$', views.item_unit_price, name="unit_price"),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name="delete"),
    url(r'^trash/$', views.trash_list, name="trash_list"),

]

transaction/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^customers/', include('customer.urls')),
    url(r'^items/', include('item.urls')),
    url(r'^units/', include('unit.urls')),
    url(r'^transactions/', include('txn.urls')),
]

txn/urls.py
from django.conf.urls import url
from . import views

app_name = "txn"

urlpatterns = [
    url(r'^index/$', views.index, name="index"),
    url(r'^list/$', views.list, name="list"),
    url(r'^paid/(?P<pk>\d+)/$', views.paid, name="paid"),
]

item/models.py
from django.db import models
from django.utils import timezone
from unit.models import Unit


class Item(models.Model):
    iname = models.CharField(max_length=20)
    unit = models.ForeignKey(Unit, related_name="items", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    class Meta:
        db_table = 'items'
        verbose_name = 'Item'
        verbose_name_plural = 'Items'

    def __str__(self):
        return self.iname

item/forms.py
from django import forms
from .models import Item


class ItemCreateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'iname',
            'unit',
            'price',
        ]
        widgets = {
            'iname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Item Name'}),
            'unit': forms.Select(attrs={'class': 'form-control', }),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Price'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['unit'].empty_label = 'Select Unit'

item/views.py
import json

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from .models import Item
from .forms import ItemCreateForm


def create(request):
    form = ItemCreateForm(request.POST or None)
    context = {}

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect("item:list")
    context['form'] = form
    return render(request, 'item/create.html', context)


def edit(request, pk):
    context = {}
    try:
        data = Item.objects.get(id=pk)
    except Item.DoesNotExist:
        messages.error(request, 'Data not found')
        return redirect('item:list')
    form = ItemCreateForm(instance=data)
    if request.method == 'POST':
        form = ItemCreateForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return redirect('item:list')

    context['form'] = form
    return render(request, 'item/create.html', context)


def delete(request, pk):
    context = {}
    choice = request.GET.get('choice')
    context['status'] = choice

    if request.method == "POST":
        try:
            data = Item.objects.get(id=pk)
        except Item.DoesNotExist:
            messages.error(request, "Item not found")
            return redirect("item:list")

        if choice == "undo":
            data.is_deleted = False
            data.save()
            messages.success(request, 'Undo successfully.')

        elif choice == "Trash":
            data.is_deleted = True
            data.save()
            messages.success(request, 'Trashed successfully.')

        elif choice == "delete" and data.is_deleted is True:
            data.delete()
            messages.success(request, 'Deleted successfully.')

        return redirect("item:list")

    context['url'] = reverse("item:list")
    return render(request, 'snippest/delete.html', context)


def list(request):
    context = {}
    data = Item.objects.filter(is_deleted=False)

    per_page = 2
    paginator = Paginator(data, per_page)
    page = request.GET.get('page')

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    context['data'] = data
    return render(request, 'item/list.html', context)


def trash_list(request):
    context = {}
    data = Item.objects.filter(is_deleted=True)

    per_page = 2
    paginator = Paginator(data, per_page)
    page = request.GET.get('page')
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    context['data'] = data
    return render(request, 'item/list.html', context)


def item_unit_price(request, pk):
    try:
        data = Item.objects.get(id=pk)
    except Item.DoesNotExist:
        return HttpResponse("Unable to find data.", status=400)

    context = {"unit_price": str(data.price)}
    context = json.dumps(context)
    return HttpResponse(context, "application/json", status=200)

item/templates/item/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block breadcrumb_link %}
    <li class="breadcrumb-item"><a href="{% url 'item:list' %}">Item</a></li>
    <li class="breadcrumb-item active" aria-current="page">New</li>
{% endblock %}

{% block content %}
    <div class="container" id="form_layout">
        <div class="row mt-5">
            <div class="col-md-8 offset-md-2">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Item Name</label>
                        {% if form.iname.errors %}
                            <div class="col-sm-8">
                                {{ form.iname | add_class:"is-invalid" }}
                                <div class="invalid-feedback">
                                    {{ form.iname.errors }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-sm-8">
                                {{ form.iname }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Unit</label>
                        {% if form.unit.errors %}
                            <div class="col-sm-8">
                                {{ form.unit | add_class:"is-invalid" }}
                                <div class="invalid-feedback">
                                    {{ form.unit.errors }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-sm-8">
                                {{ form.unit }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Price</label>
                        {% if form.price.errors %}
                            <div class="col-sm-8">
                                {{ form.price | add_class:"is-invalid" }}
                                <div class="invalid-feedback">
                                    {{ form.price.errors }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-sm-8">
                                {{ form.price }}
                            </div>
                        {% endif %}
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-8 offset-sm-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

item/templates/item/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block breadcrumb_link %}
    <li class="breadcrumb-item active" aria-current="page">Item</li>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row ">
            <a href="{% url 'item:create' %}" class=" btn btn-primary"><i class="fa fa-plus"> </i> Add</a>
        </div>
        <br>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Item Name</th>
                        <th>Unit</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                    </thead>
                    {% for datum in data %}
                        <tr>
                            <td> {{ datum.iname }} </td>
                            <td> {{ datum.unit }} </td>
                            <td> {{ datum.price }} </td>
                            <td>
                                {% if not datum.is_deleted %}
                                    <a href="{% url 'item:edit' datum.id %}" class="btn">
                                        <i class="fa fa-2x fa-pencil-square-o"></i></a>
                                    <a href="{% url 'item:delete' datum.id %}?choice=Trash" class="btn">
                                        <i class="fa fa-2x fa-trash-o text-danger"></i></a>
                                {% else %}
                                    <a href="{% url 'item:delete' datum.id %}?choice=undo" class=" btn">
                                        <i class="fa fa-2x fa-undo"></i>
                                    </a>
                                    <a href="{% url 'item:delete' datum.id %}?choice=delete" class=" btn">
                                        <i class="fa fa-2x fa-trash text-danger"></i>
                                    </a>
                                {% endif %}
                            </td>
                            {% empty %}
                        <tr>
                            <td class="table-danger text-center" colspan="6" >No Data</td>
                        </tr>
                        </tr>
                    {% endfor %}
                </table>

                <div class="text-center">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if data.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ data.previous_page_number }}" tabindex="-1">&laquo; Previous</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link" href="#">&laquo; Previous</a></li>
                            {% endif %}

                            {% for i in data.paginator.page_range %}
                                {% if data.number == i %}
                                    <li class="page-item disabled">
                                        <a class="page-link " href="#">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}


                            {% if data.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}">Next
                                    &raquo;</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link">Next &raquo;</a></li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}